name: Docker Javascript Image CI

on:
  workflow_dispatch:


jobs:

  build_image_and_deploy_it_on_registry:
    env:
      DOCKERFILE: javascript.dockerfile
      REPOSITORY: ${{ secrets.DOCKER_HUB_REGISTRY }}/edc-javascript

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build .  --file ${{ env.DOCKERFILE }} --tag edc-javascript:$(date +%s)

    # https://github.com/docker/login-action
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # https://github.com/docker/build-push-action
    - name: Push Docker image with release version
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ env.DOCKERFILE }}
        push: true
        tags: ${{ env.REPOSITORY }}:latest