name: Docker Alpine Image CD

on:
  workflow_dispatch:
    inputs:
      image_version:
        description: 'Image Version'
        required: true
jobs:

  build_image_and_deploy_it_on_registry:
    env:
      DOCKERFILE: alpine.dockerfile
      REPOSITORY: ${{ secrets.DOCKER_HUB_REGISTRY }}/edc-alpine

    runs-on: ubuntu-latest

    steps:
    # https://github.com/actions/checkout
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file ${{ env.DOCKERFILE }} --tag edc-alpine:$(date +%s)

    # https://github.com/docker/login-action
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # https://github.com/docker/build-push-action
    - name: Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ env.DOCKERFILE }}
        push: true
        tags: ${{ env.REPOSITORY }}:v.${{ inputs.image_version }}

    # https://github.com/docker/build-push-action
    - name: Push Docker image with latest version
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ env.DOCKERFILE }}
        push: true
        tags: ${{ env.REPOSITORY }}:latest